import {
  RailwaySection,
  Train,
  TrainSchedule,
  TrainOperationsResponse,
} from "@/types";

export const DEFAULT_RAILWAY_SECTIONS: RailwaySection[] = [
  {
    id: 1,
    section_name: "New Delhi - Mathura",
    origin_station: "New Delhi",
    source_station_code: "NDLS",
    end_station: "Mathura",
    destination_station_code: "MTJ",
    distance: 141.0,
    status: true,
  },
  {
    id: 2,
    section_name: "Mathura - Agra Cantt",
    origin_station: "Mathura",
    source_station_code: "MTJ",
    end_station: "Agra Cantt",
    destination_station_code: "AGC",
    distance: 54.0,
    status: true,
  },
  {
    id: 3,
    section_name: "Agra Cantt - Gwalior",
    origin_station: "Agra Cantt",
    source_station_code: "AGC",
    end_station: "Gwalior",
    destination_station_code: "GWL",
    distance: 118.0,
    status: true,
  },
  {
    id: 4,
    section_name: "Gwalior - VGL Jhansi",
    origin_station: "Gwalior",
    source_station_code: "GWL",
    end_station: "VGL Jhansi",
    destination_station_code: "VGLJ",
    distance: 98.0,
    status: true,
  },
  {
    id: 5,
    section_name: "VGL Jhansi - Bina",
    origin_station: "VGL Jhansi",
    source_station_code: "VGLJ",
    end_station: "Bina",
    destination_station_code: "BINA",
    distance: 153.0,
    status: true,
  },
  {
    id: 6,
    section_name: "Bina - Bhopal",
    origin_station: "Bina",
    source_station_code: "BINA",
    end_station: "Bhopal",
    destination_station_code: "BPL",
    distance: 139.0,
    status: true,
  },
  {
    id: 7,
    section_name: "Bhopal - Ratlam",
    origin_station: "Bhopal",
    source_station_code: "BPL",
    end_station: "Ratlam",
    destination_station_code: "RTM",
    distance: 260.0,
    status: true,
  },
  {
    id: 8,
    section_name: "Ratlam - Vadodara",
    origin_station: "Ratlam",
    source_station_code: "RTM",
    end_station: "Vadodara",
    destination_station_code: "BRC",
    distance: 260.0,
    status: true,
  },
  {
    id: 9,
    section_name: "Vadodara - Surat",
    origin_station: "Vadodara",
    source_station_code: "BRC",
    end_station: "Surat",
    destination_station_code: "ST",
    distance: 129.0,
    status: true,
  },
  {
    id: 10,
    section_name: "Surat - Mumbai Central",
    origin_station: "Surat",
    source_station_code: "ST",
    end_station: "Mumbai Central",
    destination_station_code: "MMCT",
    distance: 259.0,
    status: true,
  },
];

export const DEFAULT_TRAINS: Train[] = [
  { id: 219, train_number: "12442", name: "BSP RAJDHNI EXP", train_type: "RAJDHANI", priority: 10 },
  { id: 220, train_number: "12612", name: "MAS GARIB RATH", train_type: "EXPRESS", priority: 7 },
  { id: 221, train_number: "12550", name: "MCTM DURG SF EXP", train_type: "EXPRESS", priority: 8 },
  { id: 200, train_number: "12716", name: "ASR NED SF EXP", train_type: "EXPRESS", priority: 7 },
  { id: 178, train_number: "22458", name: "AADR NED SF EXP", train_type: "EXPRESS", priority: 8 },
  { id: 170, train_number: "12722", name: "DAKSHIN EXP", train_type: "EXPRESS", priority: 6 },
  { id: 101, train_number: "64074", name: "NDLS-DHO EMU", train_type: "PASSENGER", priority: 5 },
  { id: 102, train_number: "12138", name: "PUNJAB MAIL", train_type: "EXPRESS", priority: 6 },
  { id: 103, train_number: "12002", name: "SHATABDI EXPRES", train_type: "SHATABDI", priority: 10 },
  { id: 104, train_number: "12280", name: "TAJ EXPRESS", train_type: "EXPRESS", priority: 6 },
  { id: 105, train_number: "20452", name: "NDLS SGAC SF EX", train_type: "EXPRESS", priority: 8 },
  { id: 106, train_number: "11906", name: "HSX AGC EXP", train_type: "EXPRESS", priority: 6 },
  { id: 107, train_number: "11078", name: "JHELUM EXPRESS", train_type: "EXPRESS", priority: 6 },
  { id: 108, train_number: "12724", name: "TELANGANA EXP", train_type: "EXPRESS", priority: 6 },
  { id: 109, train_number: "12616", name: "GRAND TRUNK EXP", train_type: "EXPRESS", priority: 6 },
  { id: 110, train_number: "14212", name: "INTERCITY EXP", train_type: "EXPRESS", priority: 6 },
  { id: 111, train_number: "12628", name: "KARNATAKA EXP", train_type: "EXPRESS", priority: 6 },
  { id: 112, train_number: "12920", name: "MALWA EXPRESS", train_type: "EXPRESS", priority: 6 },
  { id: 113, train_number: "11058", name: "ASR CSMT EXP", train_type: "EXPRESS", priority: 6 },
];

export const DEFAULT_TRACKED_OPERATIONS: TrainOperationsResponse = {
  date: "2026-09-04",
  source: "NDLS",
  destination: "MTJ",
  count: 14,
  trains: [
    {
      train_number: "64074",
      train_name: "NDLS-DHO EMU",
      train_type: "PASSENGER",
      priority: 5,
      delay_minutes: 1,
      section: {
        name: "New Delhi - Mathura",
        source: "New Delhi",
        source_code: "NDLS",
        destination: "Mathura",
        destination_code: "MTJ",
      },
      schedule: {
        entry_time: "04:15:00",
        exit_time: "08:10:00",
      },
      movement: {
        actual_entry_time: "2026-09-03T22:46:00Z",
        actual_exit_time: "2026-09-04T03:17:00Z",
      },
    },
    {
      train_number: "12138",
      train_name: "PUNJAB MAIL",
      train_type: "EXPRESS",
      priority: 6,
      delay_minutes: 1440,
      section: {
        name: "New Delhi - Mathura",
        source: "New Delhi",
        source_code: "NDLS",
        destination: "Mathura",
        destination_code: "MTJ",
      },
      schedule: {
        entry_time: "05:10:00",
        exit_time: "07:23:00",
      },
      movement: {
        actual_entry_time: "2026-09-04T23:40:00Z",
        actual_exit_time: "2026-09-05T01:53:00Z",
      },
    },
    {
      train_number: "12002",
      train_name: "SHATABDI EXPRES",
      train_type: "SHATABDI",
      priority: 10,
      delay_minutes: 1,
      section: {
        name: "New Delhi - Mathura",
        source: "New Delhi",
        source_code: "NDLS",
        destination: "Mathura",
        destination_code: "MTJ",
      },
      schedule: {
        entry_time: "06:00:00",
        exit_time: "07:19:00",
      },
      movement: {
        actual_entry_time: "2026-09-04T00:31:00Z",
        actual_exit_time: "2026-09-04T02:05:00Z",
      },
    },
    {
      train_number: "12280",
      train_name: "TAJ EXPRESS",
      train_type: "EXPRESS",
      priority: 6,
      delay_minutes: 2,
      section: {
        name: "New Delhi - Mathura",
        source: "New Delhi",
        source_code: "NDLS",
        destination: "Mathura",
        destination_code: "MTJ",
      },
      schedule: {
        entry_time: "06:55:00",
        exit_time: "08:35:00",
      },
      movement: {
        actual_entry_time: "2026-09-04T01:27:00Z",
        actual_exit_time: "2026-09-04T03:30:00Z",
      },
    },
    {
      train_number: "20452",
      train_name: "NDLS SGAC SF EX",
      train_type: "EXPRESS",
      priority: 8,
      delay_minutes: 1,
      section: {
        name: "New Delhi - Mathura",
        source: "New Delhi",
        source_code: "NDLS",
        destination: "Mathura",
        destination_code: "MTJ",
      },
      schedule: {
        entry_time: "07:10:00",
        exit_time: "08:55:00",
      },
      movement: {
        actual_entry_time: "2026-09-04T01:41:00Z",
        actual_exit_time: "2026-09-04T03:35:00Z",
      },
    },
    {
      train_number: "11906",
      train_name: "HSX AGC EXP",
      train_type: "EXPRESS",
      priority: 6,
      delay_minutes: 1440,
      section: {
        name: "New Delhi - Mathura",
        source: "New Delhi",
        source_code: "NDLS",
        destination: "Mathura",
        destination_code: "MTJ",
      },
      schedule: {
        entry_time: "07:20:00",
        exit_time: "09:23:00",
      },
      movement: {
        actual_entry_time: "2026-09-05T01:50:00Z",
        actual_exit_time: "2026-09-05T03:53:00Z",
      },
    },
    {
      train_number: "11078",
      train_name: "JHELUM EXPRESS",
      train_type: "EXPRESS",
      priority: 6,
      delay_minutes: 1440,
      section: {
        name: "New Delhi - Mathura",
        source: "New Delhi",
        source_code: "NDLS",
        destination: "Mathura",
        destination_code: "MTJ",
      },
      schedule: {
        entry_time: "11:30:00",
        exit_time: "13:15:00",
      },
      movement: {
        actual_entry_time: "2026-09-05T06:00:00Z",
        actual_exit_time: "2026-09-05T07:45:00Z",
      },
    },
    {
      train_number: "12716",
      train_name: "SACHKHAND EXP",
      train_type: "EXPRESS",
      priority: 6,
      delay_minutes: 3,
      section: {
        name: "New Delhi - Mathura",
        source: "New Delhi",
        source_code: "NDLS",
        destination: "Mathura",
        destination_code: "MTJ",
      },
      schedule: {
        entry_time: "13:00:00",
        exit_time: "14:31:00",
      },
      movement: {
        actual_entry_time: "2026-09-04T07:33:00Z",
        actual_exit_time: "2026-09-04T09:22:00Z",
      },
    },
    {
      train_number: "12724",
      train_name: "TELANGANA EXP",
      train_type: "EXPRESS",
      priority: 6,
      delay_minutes: 1,
      section: {
        name: "New Delhi - Mathura",
        source: "New Delhi",
        source_code: "NDLS",
        destination: "Mathura",
        destination_code: "MTJ",
      },
      schedule: {
        entry_time: "16:00:00",
        exit_time: "17:26:00",
      },
      movement: {
        actual_entry_time: "2026-09-04T10:31:00Z",
        actual_exit_time: "2026-09-04T12:19:00Z",
      },
    },
    {
      train_number: "12616",
      train_name: "GRAND TRUNK EXP",
      train_type: "EXPRESS",
      priority: 6,
      delay_minutes: 1,
      section: {
        name: "New Delhi - Mathura",
        source: "New Delhi",
        source_code: "NDLS",
        destination: "Mathura",
        destination_code: "MTJ",
      },
      schedule: {
        entry_time: "16:10:00",
        exit_time: "17:40:00",
      },
      movement: {
        actual_entry_time: "2026-09-04T10:41:00Z",
        actual_exit_time: "2026-09-04T12:57:00Z",
      },
    },
    {
      train_number: "14212",
      train_name: "INTERCITY EXP",
      train_type: "EXPRESS",
      priority: 6,
      delay_minutes: 0,
      section: {
        name: "New Delhi - Mathura",
        source: "New Delhi",
        source_code: "NDLS",
        destination: "Mathura",
        destination_code: "MTJ",
      },
      schedule: {
        entry_time: "17:40:00",
        exit_time: "20:13:00",
      },
      movement: {
        actual_entry_time: "2026-09-04T12:10:00Z",
        actual_exit_time: "2026-09-04T14:43:00Z",
      },
    },
    {
      train_number: "12628",
      train_name: "KARNATAKA EXP",
      train_type: "EXPRESS",
      priority: 6,
      delay_minutes: 0,
      section: {
        name: "New Delhi - Mathura",
        source: "New Delhi",
        source_code: "NDLS",
        destination: "Mathura",
        destination_code: "MTJ",
      },
      schedule: {
        entry_time: "20:20:00",
        exit_time: "21:50:00",
      },
      movement: {
        actual_entry_time: "2026-09-04T14:50:00Z",
        actual_exit_time: "2026-09-04T16:20:00Z",
      },
    },
    {
      train_number: "12920",
      train_name: "MALWA EXPRESS",
      train_type: "EXPRESS",
      priority: 6,
      delay_minutes: 0,
      section: {
        name: "New Delhi - Mathura",
        source: "New Delhi",
        source_code: "NDLS",
        destination: "Mathura",
        destination_code: "MTJ",
      },
      schedule: {
        entry_time: "20:30:00",
        exit_time: "22:38:00",
      },
      movement: {
        actual_entry_time: "2026-09-04T15:00:00Z",
        actual_exit_time: "2026-09-04T17:08:00Z",
      },
    },
    {
      train_number: "11058",
      train_name: "ASR CSMT EXP",
      train_type: "EXPRESS",
      priority: 6,
      delay_minutes: 0,
      section: {
        name: "New Delhi - Mathura",
        source: "New Delhi",
        source_code: "NDLS",
        destination: "Mathura",
        destination_code: "MTJ",
      },
      schedule: {
        entry_time: "20:40:00",
        exit_time: "22:50:00",
      },
      movement: {
        actual_entry_time: "2026-09-04T15:10:00Z",
        actual_exit_time: "2026-09-04T17:20:00Z",
      },
    },
  ],
};

export const DEFAULT_TRAIN_SCHEDULES: TrainSchedule[] = [
  {
    id: 264,
    train: 200,
    train_name: "ASR NED SF EXP",
    section: 4,
    section_name: "Gwalior-Jhansi",
    scheduled_entry_time: "03:00:00",
    scheduled_exit_time: "04:30:00",
    running_days: "0100000",
    is_active: true,
  },
  {
    id: 265,
    train: 178,
    train_name: "AADR NED SF EXP",
    section: 4,
    section_name: "Gwalior-Jhansi",
    scheduled_entry_time: "03:00:00",
    scheduled_exit_time: "04:30:00",
    running_days: "0000100",
    is_active: true,
  },
  {
    id: 266,
    train: 170,
    train_name: "DAKSHIN EXP",
    section: 4,
    section_name: "Gwalior-Jhansi",
    scheduled_entry_time: "03:22:00",
    scheduled_exit_time: "05:02:00",
    running_days: "1111111",
    is_active: true,
  },
  {
    id: 267,
    train: 171,
    train_name: "URJADHANI EXP",
    section: 4,
    section_name: "Gwalior-Jhansi",
    scheduled_entry_time: "03:41:00",
    scheduled_exit_time: "05:10:00",
    running_days: "0100100",
    is_active: true,
  },
  {
    id: 268,
    train: 172,
    train_name: "NZM ABKP SF EXP",
    section: 4,
    section_name: "Gwalior-Jhansi",
    scheduled_entry_time: "03:41:00",
    scheduled_exit_time: "05:10:00",
    running_days: "0010000",
    is_active: true,
  },
  {
    id: 269,
    train: 201,
    train_name: "GWL PRYJ EXP",
    section: 4,
    section_name: "Gwalior-Jhansi",
    scheduled_entry_time: "05:00:00",
    scheduled_exit_time: "07:15:00",
    running_days: "1111111",
    is_active: true,
  },
  {
    id: 270,
    train: 202,
    train_name: "CHAMBAL EXPRESS",
    section: 4,
    section_name: "Gwalior-Jhansi",
    scheduled_entry_time: "07:40:00",
    scheduled_exit_time: "09:10:00",
    running_days: "0100010",
    is_active: true,
  },
  {
    id: 101,
    train: 101,
    train_name: "NDLS-DHO EMU",
    section: 1,
    section_name: "New Delhi - Mathura",
    scheduled_entry_time: "04:15:00",
    scheduled_exit_time: "08:10:00",
    running_days: "1111111",
    is_active: true,
  },
  {
    id: 102,
    train: 102,
    train_name: "PUNJAB MAIL",
    section: 1,
    section_name: "New Delhi - Mathura",
    scheduled_entry_time: "05:10:00",
    scheduled_exit_time: "07:23:00",
    running_days: "1111111",
    is_active: true,
  },
  {
    id: 103,
    train: 103,
    train_name: "SHATABDI EXPRES",
    section: 1,
    section_name: "New Delhi - Mathura",
    scheduled_entry_time: "06:00:00",
    scheduled_exit_time: "07:19:00",
    running_days: "1111110",
    is_active: true,
  },
];
